import "./globals.css";
import { AgentProvider } from "@/context/AgentContext";

export const metadata = {
  title: "Talk to agents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <AgentProvider>
        {children}
        </AgentProvider>
      </body>
    </html>
  );
}
